import type { Metadata } from "next";

export const siteUrl = "https://2ko.co.za";

// Note: the default OG image is generated by app/opengraph-image.tsx
// (Next.js convention) — no static /og-image.png asset is shipped.
export const defaultMetadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: "2KO — Operational Excellence & AI Systems",
    template: "%s | 2KO",
  },
  description:
    "2KO makes operational improvement permanent through Lean Six Sigma mastery and AI-powered management systems for complex organisations.",
  openGraph: {
    siteName: "2KO",
    type: "website",
    locale: "en_ZA",
    url: siteUrl,
  },
  twitter: {
    card: "summary_large_image",
  },
  robots: {
    index: true,
    follow: true,
  },
};

export function pageMetadata(
  title: string,
  description: string,
  path = ""
): Metadata {
  const canonicalPath = path || "/";
  const pageUrl = canonicalPath === "/" ? siteUrl : `${siteUrl}${canonicalPath}`;

  return {
    title,
    description,
    alternates: {
      canonical: canonicalPath,
    },
    openGraph: {
      title,
      description,
      url: pageUrl,
    },
  };
}
